from selenium import webdriver
import unittest
import time
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import Keys


class Omint(unittest.TestCase):
    def setUp(self):
        self.drive = webdriver.Chrome(r'C:\Users\Mañana\Documents\Automation\Browser\chromedriver.exe')
        self.drive.get('https://oaapp.eastus2.cloudapp.azure.com:8600/')
        self.drive.maximize_window()

    def test_inicio(self):
        self.drive.find_element_by_xpath('//*[@id="dni"]').send_keys('49709124')
        time.sleep(1)
        self.drive.find_element_by_xpath('//*[@id="user"]').send_keys('prueba123')
        time.sleep(1)
        self.drive.find_element_by_xpath('//*[@id="password"]').send_keys('p12345')
        time.sleep(1)
        self.drive.find_element_by_xpath('//*[@id="root"]/div/div/div/form/button').click()
        time.sleep(3)
        solicitud = self.drive.find_element_by_xpath('//*[@id="root"]/div/header/div/div[1]/div[3]')
        autorizacion = self.drive.find_element_by_xpath('//*[@id="root"]/div/header/div/div[1]/div[3]/div/div[1]/a')
        action = ActionChains(self.drive)
        action.move_to_element(solicitud)
        time.sleep(3)
        action.click(autorizacion)
        action.perform()
        time.sleep(3)
        generar_autorizacion = self.drive.find_element_by_xpath('//*[@id="root"]/div/main/div/div/div[2]/div/div/a')
        generar_autorizacion.click()
        time.sleep(3)
        seleccionar = self.drive.find_element_by_xpath('/html/body/div[1]/div/main/div/div/div[3]/form/div/div/div/div[1]')
        seleccionar.click()
        time.sleep(2)
        nombre_elegir = self.drive.find_element_by_xpath('//*[@id="beneficiary"]/div/div[1]/div[1]/span')
        nombre_elegir.click()
        time.sleep(2)
        siguiente = self.drive.find_element_by_xpath('//*[@id="root"]/div/main/div/div/div[3]/form/button')
        siguiente.click()
        time.sleep(2)
        elegir_tratamiento = self.drive.find_element_by_xpath('/html/body/div[1]/div/main/div/div/div[3]/form/div/div/div[1]/div[1]')
        elegir_tratamiento.click()
        time.sleep(2)
        seleccionar_tratamiento = self.drive.find_element_by_xpath('// *[ @ id = "react-select-4-option-0-0"]')
        seleccionar_tratamiento.click()
        time.sleep(2)
        avanzar = self.drive.find_element_by_xpath('//*[@id="root"]/div/main/div/div/div[3]/form/button')
        avanzar.click()
        time.sleep(2)
        elegir_localidad = self.drive.find_element_by_xpath('//*[@id="locality"]/div/div[1]')
        elegir_localidad.click()
        time.sleep(2)
        seleccionar_localidad = self.drive.find_element_by_xpath('/html/body/div[1]/div/main/div/div/div[3]/form/div[1]/div[1]/div/div[2]/div/div[1]/div[2]/div/span').click()
        time.sleep(10)
        elegir_lugar = self.drive.find_element_by_xpath('//*[@id="place"]/div/div[1]/div[1]').click()
        time.sleep(2)
        opcion = self.drive.find_element_by_xpath('//*[@id="react-select-6-option-0"]').click()
        time.sleep(2)
        nombre_clinica = self.drive.find_element_by_xpath('/html/body/div[1]/div/main/div/div/div[3]/div/dialog/form/div[1]/div/input')
        print("hasta aca funca")
        print(nombre_clinica.is_enabled())
        nombre_clinica.send_keys('Bazterrica')
        time.sleep(2)
        btn_siguiente = self.drive.find_element_by_xpath('//*[@id="root"]/div/main/div/div/div[3]/div/dialog/form/div[3]/button[2]')
        btn_siguiente.click()
        time.sleep(1)
        fecha = self.drive.find_element_by_xpath('//*[@id="date"]').send_keys('06022020')
        time.sleep(2)
        comentarios = self.drive.find_element_by_xpath('//*[@id="observations"]').send_keys('esta es una prueba automatizada')
        time.sleep(2)
        subir = self.drive.find_element_by_id('file').send_keys(r'C:\Users\Mañana\Desktop\omint.jpg')
        time.sleep(5)
        finalizar_consulta = self.drive.find_element_by_xpath('//*[@id="root"]/div/main/div/div/div[3]/form/button')
        finalizar_consulta.click()
        time.sleep(5)
        perfil = self.drive.find_element_by_xpath('//*[@id="root"]/div/header/div/div[1]/div[4]')
        salir = self.drive.find_element_by_xpath('//*[@id="root"]/div/header/div/div[1]/div[4]/div/div[1]/button')
        action = ActionChains(self.drive)
        action.move_to_element(perfil)
        time.sleep(1)
        action.click(salir)
        action.perform()
        time.sleep(3)

    def tearDown(self):
        self.drive.quit()